SELECT SUSER_SNAME() + (CASE IS_MEMBER('ANIVN_AzureADSQLUsers') WHEN 1 THEN ' Is a Member of ANIVN_AzureADSQLUsers' ELSE ' Is Not a Member of ANIVN_AzureADSQLUsers' END)

--CREATE USER [ANIVN_AzureADSQLUsers] FROM EXTERNAL PROVIDER;